### ISSUE TITLE
derivative page images don't get created

### ISSUE THREAD

**Issue by jpeak5** [lsulibraries/repository#5]
When creating an Internet Archive Book, page images should be created, however, there are no image datastreams in either the book its pages...

**Comment by rtilla1** [comment]
See https://github.com/lsulibraries/repository/wiki/Internet-Archive-Book-Viewer-Issues for more information.

**Comment by jpeak5** [comment]
Ghostscript appears to be installed correctly: 
http://rtilla1.dsl.lsu.edu/admin/islandora/solution_pack_config/paged_content

**Comment by rtilla1** [comment]
Pages are being created in 5/6 upload scenarios--display issues are being caused elsewhere
